_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
SOLVER:
#  AMP:
#    ENABLED: True
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
#  MAX_ITER: 180000
  STEPS: (69990, 69995)
  MAX_ITER: 70000
#  IMG_PER_BATCH_LABEL: 16
#  IMG_PER_BATCH_UNLABEL: 16
  IMG_PER_BATCH_LABEL: 2
  IMG_PER_BATCH_UNLABEL: 2
#  IMS_PER_BATCH: 4
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  LABEL_NUMS: 5011
  TRAIN: ("voc_2012_trainval",)
  TRAIN_LABEL: ("voc_2007_trainval",)
  TRAIN_UNLABEL: ("voc_2012_trainval",)
  TEST: ("voc_2007_test",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
#  BURN_UP_STEP: 10000
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 2.0
TEST:
  EVAL_PERIOD: 3000
#  EVAL_PERIOD: 100
  EVALUATOR: "COCOeval"
#  EVALUATOR:"VOCevaluator"
